plugins {
    id 'com.android.application'
}

android {
    namespace 'app.rota.estudos'
    compileSdk 36

    defaultConfig {
        applicationId 'app.rota.estudos'
        minSdk 23
        targetSdk 36
        versionCode 4
        versionName '0.3.1'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        warningsAsErrors true
        checkReleaseBuilds true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += ['-Xlint:deprecation']
}

dependencies {
    testImplementation 'junit:junit:4.13.2'

    androidTestImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
}
